Repository taichi-dev/taichi, pull requests merged in 2020-06, with the labels that each got.

#1098 [cli] [example] Support running examples with python file extension
  python/taichi/main.py
Labels: GAMES201

#1127 [misc] tell users to check troubleshooting page when error occurred
  docs/install.rst
  python/taichi/core/util.py
  python/taichi/main.py
  taichi/system/traceback.cpp
Labels: GAMES201, error-message, skip ci

#1121 [Lang] [refactor] shows an error if not called from correct Taichi/Python-scope
  python/taichi/core/util.py
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  python/taichi/lang/kernel.py
  python/taichi/lang/matrix.py
  python/taichi/lang/util.py
  python/taichi/misc/gui.py
Labels: GAMES201, error-message

#1143 [Lang] [IR] Fix bound checks with coordinate offsets
  taichi/transforms/check_out_of_bound.cpp
  tests/python/test_debug.py
Labels: GAMES201, ir

#1139 [metal] Add APIs to list all the available Metal devices
  taichi/backends/metal/api.cpp
  taichi/backends/metal/api.h
  taichi/platform/mac/objc_api.cpp
  taichi/platform/mac/objc_api.h
Labels: metal

#1051 [Lang] Support Python-scope matrix/vector operations
  README.md
  docs/matrix.rst
  python/taichi/lang/common_ops.py
  python/taichi/lang/matrix.py
  tests/python/test_matrix.py
  tests/python/test_numpy_io.py
Labels: GAMES201, stale

#1144 [llvm] Cache llvm runtime bitcode to reduce start up time in dev mode
  docs/global_settings.rst
  taichi/llvm/llvm_context.cpp
Labels: llvm

#1149 [example] [refactor] Rename some old examples to avoid confusing people
  examples/gui_image_io.py
  examples/ml_minimization_trivial.py
  examples/ml_regression.py
  examples/mlp.py
  examples/mnist.py
  examples/mnist_download_data.py
  examples/pytorch_tensor_ad.py
  examples/pytorch_tensor_io.py
  examples/taichi_autodiff.py
  examples/taichi_bitmasked.py
  examples/taichi_dynamic.py
  misc/copyright.py
  misc/minimal.py
Labels: enhancement, skip ci

#1148 [doc] Better coordinate offset documentation
  docs/index.rst
  docs/matrix.rst
  docs/offset.rst
  docs/scalar_tensor.rst
  docs/vector.rst
Labels: doc, skip ci

#1162 [gui] [Bug] Fix keyboard event loss problem on specific Win OS version
  taichi/gui/win32.cpp
Labels: waiting for reply

#1152 [GUI] Add ti.GUI.EXIT event to close a window
  docs/gui.rst
  examples/euler.py
  examples/game_of_life.py
  examples/keyboard.py
  examples/mpm128.py
  examples/mpm88.py
  examples/mpm99.py
  examples/nbody_oscillator.py
  examples/pbf2d.py
  examples/quadtree.py
  examples/taichi_logo.py
  examples/waterwave.py
  python/taichi/misc/gui.py
  python/taichi/misc/image.py
  taichi/gui/gui.h
  taichi/gui/win32.cpp
  taichi/gui/x11.cpp
  taichi/python/export_visual.cpp
Labels: linux, rendering, skip ci, windows

#1165 [misc] Add some links to README.md
  README.md
Labels: skip ci

#1160 [Bug] [opengl] Fix AMD+OpenGL to_numpy behavior (thank @Eydcao for testing!)
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
Labels: waiting for reply

#1107 [Lang] [refactor] ti.Matrix initializers
  docs/matrix.rst
  python/taichi/lang/matrix.py
  tests/python/test_linalg.py
Labels: skip ci, waiting for reply

#1166 [OpenGL] support print 1 scalar in OpenGL kernels
  docs/syntax.rst
  examples/quadtree.py
  python/taichi/lang/impl.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_api.h
  taichi/backends/opengl/opengl_kernel_launcher.h
  taichi/backends/opengl/opengl_kernel_util.h
  taichi/backends/opengl/runtime.h
  taichi/backends/opengl/shaders/print.glsl.h
  tests/python/test_print.py
Labels: GAMES201, LGTM, opengl

#1189 [GUI] [Mac] Support modifier keys like Shift, Ctrl, etc
  python/taichi/misc/gui.py
  taichi/gui/cocoa.cpp
  taichi/gui/gui.h
Labels: GAMES201, mac

#1187 [test] Let pytest-rerunfailures pytest-xdist to be hard dependences
  docs/dev_install.rst
  misc/empty_pytest.py
  python/taichi/main.py
Labels: LGTM

#1196 [test] Setup python coverage test
  .github/pull_request_template.md
  .gitignore
  .travis.yml
  README.md
  appveyor.yml
  docs/contributor_guide.rst
  docs/dev_install.rst
  docs/utilities.rst
  misc/ci_setup.py
  python/taichi/main.py
  python/taichi/tools/messenger.py
  setup.py
Labels: skip ci

#1157 [doc] [workflow] Update hello and matrix section of the docs and add a workflow to check doc builds
  .github/workflows/docs.yml
  docs/cli_utilities.rst
  docs/dev_install.rst
  docs/hello.rst
  docs/index.rst
  docs/matrix.rst
  misc/minimal_timed.py
Labels: skip ci, waiting for reply

#1175 [metal] Add kernel side memory allocator
  taichi/backends/metal/codegen_metal.cpp
  taichi/backends/metal/kernel_manager.cpp
  taichi/backends/metal/shaders/atomic_stubs.h
  taichi/backends/metal/shaders/runtime_kernels.metal.h
  taichi/backends/metal/shaders/runtime_structs.metal.h
  taichi/backends/metal/shaders/runtime_utils.metal.h
  taichi/backends/metal/struct_metal.cpp
  taichi/backends/metal/struct_metal.h
Labels: LGTM

#1202 [doc] Improve dev_install for Windows and LLVM 10
  docs/dev_install.rst
Labels: skip ci

#1192 [doc] Improve tutorial on exporting results
  docs/export_results.rst
  docs/gui.rst
  examples/export_videos.py
Labels: doc, skip ci

#1225 [Opt] Make full_simplify iterative when advanced_optimization=True
  taichi/ir/transforms.h
  taichi/transforms/compile_to_offloads.cpp
  taichi/transforms/constant_fold.cpp
  taichi/transforms/simplify.cpp
Labels: LGTM

#1212 [CLI] Add TI_ADVANCED_OPTIMIZATION config env var
  docs/global_settings.rst
  python/taichi/lang/__init__.py
Labels: LGTM

#1219 [workflow] Add a workflow to enforce PR title format
  .github/pull_request_template.md
  .github/workflows/persubmit.yml
  .tmp_idle_source
  docs/contributor_guide.rst
  misc/check_pr_title.py
  misc/count_tags.py
  misc/prtags.json
  python/taichi/make_changelog.py
Labels: LGTM, skip ci

#1201 [Lang] Export .ply file
  docs/dev_install.rst
  docs/export_results.rst
  examples/export_mesh.py
  examples/export_ply.py
  python/taichi/__init__.py
  python/taichi/misc/np2ply.py
Labels: skip ci

#1185 [Bug] [misc] Fix image I/O for channels = 1 and improve test coverage
  README.md
  python/build.py
  python/taichi/misc/image.py
  tests/python/test_image_io.py
Labels: skip ci

#1246 [test] Add coverage threshold to make codecov not fail so easily
  codecov.yml
Labels: skip ci

#1220 [Doc] Standardize versioning and release workflow
  docs/index.rst
  docs/versioning_releases.rst
Labels: skip ci

#1209 [doc] Remove changelog link from readme
  README.md
Labels: skip ci

#1252 [Lang] Support vector unpacking (e.g., "a, b = ti.Vector([1, 2])")
  docs/differentiable_programming.rst
  docs/gui.rst
  python/taichi/lang/impl.py
  tests/python/test_tuple_assign.py
Labels: skip ci

#1244 [workflow] Improve PR title checker for the release tag
  .github/workflows/persubmit.yml
  misc/check_pr_title.py
Labels: LGTM, skip ci

#1250 [Doc] Add links to external libraries: Taichi GLSL & Taichi Elements
  docs/extension_libraries.rst
  docs/index.rst
Labels: skip ci

#1275 [lang] [test] Improve code coverage in Matrix
  .travis.yml
  appveyor.yml
  docs/syntax.rst
  python/taichi/lang/matrix.py
  tests/python/test_linalg.py
Labels: python

#1253 [Example] Improve examples/odop_solar.py visual & comments
  examples/odop_solar.py
Labels: GAMES201, skip ci

#1272 [Opt] [ir] [refactor] Remove exceptions from demote_atomics pass
  taichi/ir/ir.cpp
  taichi/ir/ir.h
  taichi/ir/transforms.h
  taichi/transforms/demote_atomics.cpp
Labels: ir

#1188 [Lang] [refactor] Support Python-scope scalar functions / matrix operations, e.g. ti.sqrt(2)
  docs/matrix.rst
  python/taichi/lang/common_ops.py
  python/taichi/lang/matrix.py
  python/taichi/lang/ops.py
  tests/python/test_constant_func.py
  tests/python/test_element_wise.py
  tests/python/test_linalg.py
  tests/python/test_matrix.py
Labels: GAMES201, error-prone, large changeset

#1273 [Misc] Postpone backend detection to prevent possible compatibility issues
  .tmp_idle_source
  examples/sdf2d.py
  python/taichi/core/util.py
  python/taichi/lang/__init__.py
  taichi/backends/opengl/opengl_api.cpp
  taichi/program/extension.cpp
  taichi/program/extension.h
  taichi/python/export_lang.cpp
Labels: skip ci

#1214 [lang] [test] Improve code coverage in SNode
  docs/snode.rst
  examples/quadtree.py
  python/taichi/lang/__init__.py
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  python/taichi/lang/snode.py
  tests/python/test_tensor_reflection.py
Labels: LGTM, large changeset

#1222 [IPython] Source inspection dispatcher for better IDLE compatibility
  Jenkinsfile
  docs/dev_install.rst
  examples/mpm128.py
  examples/stable_fluid.py
  misc/ci_setup.py
  misc/prtags.json
  python/taichi/lang/ast_checker.py
  python/taichi/lang/kernel.py
  python/taichi/lang/shell.py
  python/taichi/main.py
  setup.py
  tests/python/test_cli.py
Labels: GAMES201, LGTM

#1309 [doc] Add Taichi THREE to documentation
  README.md
  docs/extension_libraries.rst
  python/taichi/lang/expr.py
Labels: skip ci

#1326 [Bug] [linux] [opengl] Use RTLD_LOCAL to prevent LLVM symbol conflict with GLX
  python/taichi/core/util.py
Labels: LGTM

#1256 [OpenGL] [sparse] Basic support for dynamic SNode
  docs/snode.rst
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_api.h
  taichi/backends/opengl/opengl_data_types.h
  taichi/backends/opengl/opengl_kernel_launcher.h
  taichi/backends/opengl/runtime.h
  taichi/backends/opengl/struct_opengl.cpp
  tests/python/test_dynamic.py
Labels: c++, error-prone, opengl, waiting for reply

#1318 [Lang] [refactor] Deprecate x.shape() and x.dim(), use x.shape instead
  docs/vector.rst
  python/taichi/lang/expr.py
  python/taichi/lang/matrix.py
  python/taichi/lang/snode.py
  python/taichi/lang/transformer.py
  python/taichi/misc/gui.py
  tests/python/test_linalg.py
  tests/python/test_tensor_reflection.py
  tests/python/test_tuple_assign.py
Labels: LGTM

#1324 [Opt] Dead store and stack-related operation elimination by control-flow graph
  taichi/analysis/build_cfg.cpp
  taichi/analysis/data_source_analysis.cpp
  taichi/ir/analysis.h
  taichi/ir/control_flow_graph.cpp
  taichi/ir/control_flow_graph.h
  taichi/transforms/cfg_optimization.cpp
  taichi/transforms/compile_to_offloads.cpp
  taichi/transforms/ir_printer.cpp
  taichi/transforms/variable_optimization.cpp
Labels: large changeset

#1303 [IPython] [opengl] Make OpenGL kernel print work in IPython & IDLE
  docs/syntax.rst
  python/taichi/__init__.py
  python/taichi/lang/impl.py
  taichi/backends/opengl/opengl_api.cpp
  taichi/python/export_misc.cpp
  taichi/python/print_buffer.h
Labels: LGTM

#1334 [Sparse] [lang] Add ti.activate support
  misc/ci_setup.py
  python/taichi/lang/ops.py
  taichi/backends/metal/codegen_metal.cpp
  taichi/codegen/codegen_llvm.cpp
  taichi/ir/ir.cpp
  taichi/python/export_lang.cpp
  taichi/transforms/lower_ast.cpp
  tests/python/test_sparse_activate.py
  tests/python/test_sparse_deactivate.py
Labels: LGTM

#1341 [refactor] [metal] Add a TaichiKernelAttribs struct
  taichi/backends/metal/codegen_metal.cpp
  taichi/backends/metal/kernel_manager.cpp
  taichi/backends/metal/kernel_manager.h
  taichi/backends/metal/kernel_util.cpp
  taichi/backends/metal/kernel_util.h
Labels: waiting for reply

#1331 [IPython] [gui] Support inline output display in Jupyter GUI
  python/taichi/__init__.py
  python/taichi/misc/image.py
  taichi/backends/metal/shaders/print.metal.h
  taichi/python/export_misc.cpp
Labels: LGTM

#1348 [cc] Set up the experimental C language backend
  .github/workflows/persubmit.yml
  .gitignore
  cmake/TaichiCore.cmake
  hello.py
  misc/prtags.json
  python/taichi/lang/__init__.py
  taichi/backends/cc/cc_configuation.h
  taichi/backends/cc/cc_kernel.h
  taichi/backends/cc/cc_layout.h
  taichi/backends/cc/cc_program.cpp
  taichi/backends/cc/cc_program.h
  taichi/backends/cc/cc_utils.h
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/cc/codegen_cc.h
  taichi/backends/cc/struct_cc.cpp
  taichi/backends/cc/struct_cc.h
  taichi/inc/archs.inc.h
  taichi/program/kernel_profiler.cpp
  taichi/program/program.cpp
  taichi/program/program.h
  taichi/python/export_misc.cpp
  taichi/system/dynamic_loader.cpp
Labels: waiting for reply
