Repository taichi-dev/taichi, pull requests merged in 2020-08, with the labels that each got.

#1598 [infra] Support GCC as compiler for Taichi developers (experimental)
  cmake/TaichiCXXFlags.cmake
  taichi/util/action_recorder.h
Labels: LGTM

#1631 [Bug] Fix random side-effect causing SSA violation in ti.Vector
  python/taichi/lang/ops.py
  tests/python/test_linalg.py
  tests/python/test_ssa.py
Labels: LGTM

#1585 [Lang] Support float and int as aliases for default-precision data types
  python/taichi/lang/__init__.py
  python/taichi/lang/common_ops.py
  python/taichi/lang/impl.py
  python/taichi/lang/kernel.py
  python/taichi/lang/kernel_arguments.py
  python/taichi/lang/matrix.py
  python/taichi/lang/ops.py
  python/taichi/lang/util.py
  tests/python/test_cast.py
  tests/python/test_field.py
Labels: LGTM, waiting for reply

#1625 [GUI] Support gui.arrow() and gui.arrows()
  docs/gui.rst
  python/taichi/misc/gui.py
  python/taichi/misc/image.py
Labels: LGTM

#1617 [Example] Enhance stable_fluid.py with BFECC, RK2, RK3 and Taichi's new syntax
  docs/debugging.rst
  examples/stable_fluid.py
  python/taichi/lang/__init__.py
Labels: LGTM

#1612 [error] Better error messages when using wrong type annotations
  python/taichi/lang/impl.py
  python/taichi/lang/kernel.py
  tests/python/test_syntax_errors.py
Labels: wait-release, waiting for reply

#1629 [cc] Compose ActionRecorder outputs into a single C file for Emscripten
  misc/cc_action_record.py
  python/taichi/cc_compose.py
  python/taichi/core/util.py
  python/taichi/main.py
  python/taichi/testing.py
  taichi/backends/cc/cc_configuation.h
  taichi/backends/cc/context.h
  taichi/util/str.cpp
Labels: LGTM

#1650 [benchmark] Fix test_test.py benchmark including '<lambda>' in filename
  python/taichi/misc/util.py
  python/taichi/testing.py
  taichi/program/program.cpp
Labels: LGTM

#1624 [GUI] Support images with 2 channels (RG) in GUI.set_image
  docs/gui.rst
  examples/stable_fluid.py
  python/taichi/lang/meta.py
  python/taichi/misc/gui.py
Labels: LGTM, wait-release

#1611 [GUI] Support gui.fps_limit and reduce idle power consumption
  cmake/TaichiCore.cmake
  codecov.yml
  docs/gui.rst
  examples/game_of_life.py
  python/taichi/misc/gui.py
  taichi/gui/gui.h
  taichi/python/export_visual.cpp
  taichi/system/timer.cpp
  taichi/system/timer.h
Labels: LGTM

#1654 [Refactor] "x.snode()" is deprecated, use "x.snode" instead
  docs/snode.rst
  examples/comet.py
  examples/quadtree.py
  python/taichi/lang/__init__.py
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  python/taichi/lang/matrix.py
  python/taichi/lang/ops.py
  python/taichi/lang/snode.py
  tests/python/bls_test_template.py
  tests/python/test_indices.py
  tests/python/test_stop_grad.py
  tests/python/test_tensor_reflection.py
Labels: LGTM

#1595 [Example] Add cg_possion.py, a Poisson solver based on conjugate gradients
  examples/cg_possion.py
Labels: skip ci

#1649 [workflow] Add Mac OS X to Github CI
  .github/workflows/persubmit.yml
  misc/ci_check_pr_title.py
  misc/ci_download.py
Labels: LGTM

#1647 [Misc] [bug] Catch RuntimeError when detecting backends for better compatibility
  python/taichi/lang/__init__.py
  python/taichi/testing.py
Labels: LGTM

#1623 [doc] Re-update documentation on autodiff
  docs/differentiable_programming.rst
  docs/layout.rst
  docs/odop.rst
  examples/ad_gravity.py
  taichi/transforms/reverse_segments.cpp
Labels: LGTM, waiting for reply

#1661 [llvm] [linux] Further improve misc/linker.map to prevent segementation fault when importing in Blender
  misc/linker.map
Labels: LGTM, wait-release

#1653 [doc] Fix uncovered while deprecated term 'tensor' occurance
  docs/export_results.rst
  docs/hello.rst
  docs/scalar_tensor.rst
  docs/tensor_matrix.rst
  docs/write_test.rst
Labels: LGTM

#1664 [IPython] Use 'sourceinspect' to support Blender scripting module and IDLE shell
  misc/ci_setup.py
  python/taichi/lang/shell.py
  setup.py
Labels: LGTM

#1645 [cc] Add ti.cfg.cc_compile_cmd and ti.cfg.cc_link_cmd
  taichi/backends/cc/cc_config.h
  taichi/backends/cc/cc_program.cpp
  taichi/backends/cc/cc_program.h
  taichi/program/compile_config.cpp
  taichi/program/compile_config.h
  taichi/program/program.cpp
  taichi/python/export_lang.cpp
  taichi/python/export_misc.cpp
Labels: wait-release

#1576 [Doc] [refactor] Improve Taichi kernels and functions definition
  docs/global_settings.rst
  docs/hello.rst
  docs/syntax.rst
  python/taichi/lang/kernel.py
  python/taichi/misc/gui.py
Labels: LGTM, doc, skip ci, waiting for reply

#1683 [test] Replace ti.var by ti.field in tests starting with h-q
  tests/python/test_image_io.py
  tests/python/test_immediate_layout.py
  tests/python/test_indices.py
  tests/python/test_kernel_template_mapper.py
  tests/python/test_kernel_templates.py
  tests/python/test_lang.py
  tests/python/test_linalg.py
  tests/python/test_listgen.py
  tests/python/test_local_atomic_opt.py
  tests/python/test_local_atomics.py
  tests/python/test_loop_grad.py
  tests/python/test_loops.py
  tests/python/test_mod.py
  tests/python/test_mpm88.py
  tests/python/test_mpm_particle_list.py
  tests/python/test_native_functions.py
  tests/python/test_ndrange.py
  tests/python/test_new_allocator.py
  tests/python/test_no_activate.py
  tests/python/test_no_grad.py
  tests/python/test_numpy.py
  tests/python/test_numpy_io.py
  tests/python/test_offload.py
  tests/python/test_offload_cross.py
  tests/python/test_offset.py
  tests/python/test_oop.py
  tests/python/test_optimization.py
  tests/python/test_parallel_range_for.py
  tests/python/test_pow.py
  tests/python/test_print.py
  tests/python/test_ptr_assign.py
Labels: LGTM

#1639 [Example] Add mpm3d.py for dimension-independent MPM method
  examples/mpm3d.py
  examples/mpm88.py
Labels: waiting for reply

#1669 [example] [refactor] Upgrade to ti.field syntax for many examples
  docs/hello.rst
  examples/ad_gravity.py
  examples/cg_possion.py
  examples/fem128.py
  examples/fem99.py
  examples/fractal.py
  examples/game_of_life.py
  examples/mass_spring_3d.py
  examples/mpm128.py
  examples/mpm88.py
  examples/mpm99.py
  examples/mpm_lagrangian_forces.py
  examples/stable_fluid.py
Labels: skip ci

#1676 [Perf] [opengl] Support 'ti.thread_dim(x)' to change invocations per thread for OpenGL
  python/taichi/lang/__init__.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/ir/frontend_ir.h
  taichi/ir/ir.cpp
  taichi/ir/ir.h
  taichi/ir/statements.cpp
  taichi/ir/statements.h
  taichi/python/export_lang.cpp
  taichi/transforms/lower_ast.cpp
  taichi/transforms/offload.cpp
Labels: c++, error-prone, wait-release

#1652 [misc] Update README.md gallery for the newly added examples during GAMES 201
  README.md
  examples/tree_gravity.py
Labels: LGTM, skip ci, waiting for reply

#1697 [metal] Log errors if the compute kernel compilation failed
  taichi/backends/metal/api.cpp
  taichi/platform/mac/objc_api.cpp
  taichi/platform/mac/objc_api.h
Labels: LGTM

#1640 [example] [misc] Add 'ti.taichi_logo' function & misc typo fix
  docs/snode.rst
  examples/mpm3d.py
  examples/renderer_utils.py
  examples/taichi_logo.py
  examples/taichi_sparse.py
  python/taichi/lang/__init__.py
  python/taichi/lang/expr.py
  python/taichi/lang/matrix.py
  python/taichi/lang/snode.py
  python/taichi/tools/__init__.py
  python/taichi/tools/patterns.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/shaders/random.glsl.h
Labels: LGTM

#1698 [test] [refactor] Replace ti.Vector or ti.Vector.var -> ti.Vector.field
  tests/python/bls_test_template.py
  tests/python/test_assert.py
  tests/python/test_grouped.py
  tests/python/test_image_io.py
  tests/python/test_linalg.py
  tests/python/test_matrix.py
  tests/python/test_mpm88.py
  tests/python/test_mpm_particle_list.py
  tests/python/test_numpy_io.py
  tests/python/test_offset.py
  tests/python/test_print.py
  tests/python/test_random.py
  tests/python/test_ssa.py
  tests/python/test_tensor_dimensionality.py
  tests/python/test_torch_io.py
Labels: LGTM

#1677 [Doc] Add API reference for external array interactions
  docs/external.rst
  docs/index.rst
  docs/matrix.rst
  docs/vector.rst
  docs/write_test.rst
Labels: LGTM

#1705 [refactor] Fix missed ti.var -> ti.field refactors in codebase
  docs/differentiable_programming.rst
  docs/offset.rst
  docs/type.rst
  docs/write_test.rst
  examples/ad_gravity.py
  examples/odop_solar.py
  examples/simple_uv.py
  python/taichi/lang/matrix.py
  tests/python/test_ad_basics.py
  tests/python/test_bitmasked.py
  tests/python/test_element_wise.py
Labels: LGTM

#1713 [example] Make jacobi iteration 2x faster in stable_fluid.py
  examples/stable_fluid.py
Labels: LGTM

#1717 [pypi] Upgrade sourceinspect to 0.0.3 for hot fixes
  docs/dev_install.rst
  docs/meta.rst
  examples/fem128.py
  examples/fem99.py
  setup.py
Labels: LGTM, small changeset

#1721 [misc] [refactor] Replace the word tensor by field in comments and error messages
  examples/taichi_bitmasked.py
  python/taichi/lang/__init__.py
  python/taichi/lang/impl.py
  python/taichi/lang/transformer.py
  python/taichi/misc/gui.py
  python/taichi/misc/image.py
  python/taichi/tools/np2ply.py
  taichi/codegen/codegen_llvm.cpp
  taichi/ir/expr.cpp
  taichi/transforms/check_out_of_bound.cpp
  taichi/transforms/make_block_local.cpp
  taichi/transforms/make_thread_local.cpp
  taichi/transforms/type_check.cpp
  tests/python/test_image_io.py
  tests/python/test_matrix.py
  tests/python/test_ptr_assign.py
  tests/python/test_runtime.py
  tests/python/test_types.py
Labels: LGTM

#1701 [Lang] Support printing scalar fields in Python-scope
  python/taichi/lang/expr.py
  python/taichi/lang/matrix.py
  python/taichi/testing.py
  tests/python/test_print.py
Labels: wait-release

#1724 [opengl] [refactor] Use result_buffer for return value
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_kernel_launcher.h
  taichi/program/program.cpp
Labels: LGTM

#1732 [Example] Upgrade mass_spring_3d.py to Taichi THREE v0.0.3 API
  examples/mass_spring_3d.py
Labels: LGTM

#1710 [example] Upgrade pbf2d.py to new syntax
  examples/pbf2d.py
  python/taichi/testing.py
Labels: LGTM

#1726 [misc] Create misc/examples.md for more examples
  README.md
  misc/examples.md
Labels: waiting for reply

#1767 [Refactor] [lang] 'ti.var' is deprecated, use 'ti.field' instead
  python/taichi/lang/impl.py
  python/taichi/lang/matrix.py
  python/taichi/misc/util.py
Labels: LGTM

#1763 [GUI] Support gui.arrow_field() and gui.point_field() for small resolution vector / scalar field visualization
  python/taichi/misc/gui.py
Labels: LGTM

#1765 [CLI] [doc] Add 'ti repl' command for Taichi REPL shell
  docs/cli_utilities.rst
  docs/export_results.rst
  python/taichi/main.py
Labels: LGTM

#1766 [ipython] Separate {Expr,Matrix}.{__str__,__repr__} to prevent unexpected materialization when repr
  README.md
  python/taichi/lang/expr.py
  python/taichi/lang/matrix.py
  python/taichi/lang/snode.py
  tests/python/test_tensor_reflection.py
Labels: LGTM

#1761 [Doc] Separate arithmetics.rst from syntax.rst and fill it with more details
  docs/arithmetics.rst
  docs/index.rst
  docs/syntax.rst
  docs/type.rst
  python/taichi/lang/ops.py
Labels: LGTM

#1783 [error] [opengl] Better error message when int64 or sparse SNode not supported for OpenGL
  taichi/backends/metal/struct_metal.cpp
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/struct_opengl.cpp
Labels: LGTM

#1784 [Example] Fix stable_fluid.py boundary broken: int -> ti.floor, and make mpm3d.py 3x faster on CUDA
  examples/mpm3d.py
  examples/stable_fluid.py
Labels: LGTM

#1775 [Bug] [misc] Use sys.getfilesystemencoding() to prevent possible locale errors
  python/taichi/core/util.py
  taichi/python/export_lang.cpp
Labels: LGTM, urgent

#1771 [ir] [opt] Unify ifloordiv implementation over backends in demote_operations
  taichi/analysis/verify.cpp
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/ir/transforms.h
  taichi/transforms/compile_to_offloads.cpp
  taichi/transforms/demote_operations.cpp
  tests/python/test_div.py
Labels: LGTM

#1787 [Lang] [ir] Support querying external array shape by 'x.shape'
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/cuda/codegen_cuda.cpp
  taichi/backends/metal/codegen_metal.cpp
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/codegen/codegen_llvm.cpp
  taichi/codegen/codegen_llvm.h
  taichi/inc/statements.inc.h
  taichi/ir/frontend_ir.h
  taichi/ir/ir.cpp
  taichi/ir/ir.h
  taichi/python/export_lang.cpp
  taichi/transforms/ir_printer.cpp
  taichi/transforms/type_check.cpp
  tests/python/test_get_external_tensor_shape.py
Labels: LGTM

#1799 [refactor] Remove the singleton Program::context
  taichi/program/async_engine.cpp
  taichi/program/async_engine.h
  taichi/program/kernel.cpp
  taichi/program/kernel.h
  taichi/program/program.cpp
  taichi/program/program.h
  taichi/transforms/constant_fold.cpp
Labels: LGTM

#1796 [Lang] Support printing lists and tuples in Taichi-scope
  python/taichi/lang/impl.py
  python/taichi/lang/ops.py
  taichi/python/export_lang.cpp
  taichi/transforms/type_check.cpp
  tests/python/test_print.py
Labels: LGTM

#1752 [CC] [autodiff] Support AdStack on C backend
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/cc/runtime/base.h
  taichi/program/extension.cpp
Labels: LGTM

#1804 [error] Better error message when vector used as if's condition variable
  docs/arithmetics.rst
  docs/vector.rst
  python/taichi/lang/common_ops.py
  python/taichi/lang/impl.py
  python/taichi/lang/transformer.py
Labels: LGTM

#1810 [error] "Better error message when vector used as if's condition variable (#1804)"
  docs/vector.rst
  python/taichi/lang/impl.py
  python/taichi/lang/transformer.py
Labels: LGTM
