Repository taichi-dev/taichi, pull requests merged in 2020-09, with the labels that each got.

#995 [doc] Document data structure organization
  docs/compilation.rst
  docs/internal.rst
Labels: skip ci

#1819 [ir] [bug] Demote all local atomic operations, not only add
  python/taichi/misc/gui.py
  taichi/lang_util.cpp
  taichi/lang_util.h
  taichi/transforms/demote_atomics.cpp
Labels: LGTM

#1797 [Doc] Add document for XYZW accessors of vector
  docs/vector.rst
Labels: LGTM

#1691 [Doc] Add performance.rst introducing the 'ti.block_dim' API
  docs/index.rst
  docs/performance.rst
  docs/profiler.rst
Labels: LGTM

#1756 [Doc] [cc] Doc the workflow for exporting Taichi kernels to C99 source
  docs/atomic.rst
  docs/export_kernels.rst
  docs/hello.rst
  docs/index.rst
  docs/snode.rst
  docs/type.rst
  python/taichi/cc_compose.py
  python/taichi/main.py
Labels: LGTM

#1825 [ir] [bug] Fix demote_operations lacking type_check causing float16
  python/taichi/misc/image.py
  taichi/transforms/compile_to_offloads.cpp
  taichi/transforms/demote_operations.cpp
  tests/python/test_ndrange.py
Labels: urgent

#1838 [Lang] Support __len__ and __iter__ on ti.Matrix
  python/taichi/lang/matrix.py
  tests/python/test_matrix.py
Labels: LGTM

#1837 [misc] Check the previous Github workflow run status if CI is skipped
  .github/workflows/persubmit.yml
  misc/ci_check_previous_run.py
Labels: LGTM

#1794 [workflow] Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: LGTM

#1845 [pypi] Remove setuptools from hard dependencies
  docs/index.rst
  docs/internal.rst
  examples/pbf2d.py
  setup.py
Labels: small changeset

#1857 [Lang] Support ti.zero(x) and ti.one(x) for making zero/one value for the same type with x
  examples/mpm3d.py
  python/taichi/lang/impl.py
  tests/python/test_lang.py
  tests/python/test_reduction.py
Labels: LGTM

#1856 [error] [doc] Better error message when X11 environment failed to initialize
  docs/gui.rst
  taichi/gui/gui.h
  taichi/gui/x11.cpp
Labels: LGTM

#1869 [gui] [ipython] Add GUI.__del__ to close on variable dereference
  python/taichi/lang/shell.py
  python/taichi/misc/gui.py
  taichi/gui/win32.cpp
Labels: LGTM

#1764 [bug] Fix stable fluid BFECC advection
  examples/stable_fluid.py
Labels: skip ci
