Repository taichi-dev/taichi, pull requests merged in 2020-05, with the labels that each got.

#1023 [workflow] Use GitHub Actions as Linux (cpu only) CI
  .github/workflows/persubmit.yml
  docs/contributor_guide.rst
  misc/ci_setup.py
  misc/make_changelog.py
Labels: skip ci

#1038 [Lang][ir] "print()" now support strings and matrices/vectors
  python/taichi/lang/impl.py
  python/taichi/lang/matrix.py
  taichi/backends/cuda/codegen_cuda.cpp
  taichi/codegen/codegen_llvm.cpp
  taichi/ir/frontend_ir.h
  taichi/ir/ir.h
  taichi/python/export_lang.cpp
  taichi/transforms/ir_printer.cpp
  taichi/transforms/lower_ast.cpp
  taichi/transforms/vector_split.cpp
  tests/python/test_print.py
Labels: GAMES201

#1054 [lang] [refactor] Move logical operations to ops.py
  .github/pull_request_template.md
  .github/workflows/gardener.yml
  .github/workflows/persubmit.yml
  docs/matrix.rst
  docs/syntax.rst
  docs/vector.rst
  python/taichi/lang/common_ops.py
  python/taichi/lang/expr.py
  python/taichi/lang/matrix.py
  python/taichi/lang/ops.py
  python/taichi/misc/test.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/ir/expression_ops.h
  taichi/python/export_lang.cpp
  tests/python/test_element_wise.py
Labels: skip ci

#1046 [Lang] [refactor] Deprecate "as_vector=True" in Matrix.to_numpy/to_torch
  docs/external.rst
  examples/cornell_box.py
  examples/mpm88.py
  examples/quadtree.py
  examples/sdf_renderer.py
  examples/stable_fluid.py
  python/taichi/lang/__init__.py
  python/taichi/lang/matrix.py
  tests/python/test_fill.py
  tests/python/test_linalg.py
  tests/python/test_mpm88.py
  tests/python/test_numpy_io.py
  tests/python/test_torch_io.py
Labels: GAMES201

#1052 [doc] Document TaichiCon
  docs/index.rst
  docs/taichicon.rst
Labels: skip ci

#1068 [Lang] ti.cross now supports 2D vectors
  docs/scalar_tensor.rst
  docs/vector.rst
  python/taichi/lang/matrix.py
  tests/python/test_linalg.py
Labels: GAMES201, skip ci

#1031 [misc] Add a script to add copyright notices
  LICENSE
  misc/add_copyright.py
  misc/copyright.py
Labels: skip ci, stale
