Repository taichi-dev/taichi, pull requests merged in 2020-07, with the labels that each got.

#1357 [lang] Raise an error when struct-for indices number mismatch
  python/taichi/lang/impl.py
  python/taichi/lang/transformer.py
  taichi/transforms/simplify.cpp
  tests/python/test_for_group_mismatch.py
Labels: error-message

#1338 [lang] [bug] Add @ti.pyfunc for functions that work in both Taichi and Python-scope, fix matrix methods
  python/taichi/lang/__init__.py
  python/taichi/lang/impl.py
  python/taichi/lang/kernel.py
  python/taichi/lang/matrix.py
  python/taichi/lang/transformer.py
  tests/python/test_linalg.py
  tests/python/test_syntax_errors.py
Labels: LGTM

#1376 [refactor] Move c_quoted into taichi/utils/
  taichi/backends/cc/cc_utils.h
  taichi/backends/cc/codegen_cc.cpp
  taichi/util/str.cpp
  taichi/util/str.h
Labels: LGTM

#1347 [bug] [refactor] Fix error when ti.init() not called by deprecating Expr.layout_materialized
  .gitignore
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  python/taichi/lang/snode.py
  python/taichi/misc/test.py
  tests/python/test_image_io.py
  tests/python/test_runtime.py
Labels: LGTM, waiting for reply

#1352 [ir] Remove a temporary "fix_block_parents"
  taichi/transforms/compile_to_offloads.cpp
Labels: waiting for reply

#1380 [Bug] [lang] Fix @ti.func not capturing closure variables
  python/taichi/lang/kernel.py
  tests/python/test_compare.py
  tests/python/test_lexical_scope.py
  tests/python/test_syntax_errors.py
Labels: LGTM

#1350 [ir] Fix ir_printer now that print() supports end
  taichi/backends/metal/kernel_manager.cpp
  taichi/transforms/ir_printer.cpp
  tests/python/test_print.py
Labels: LGTM

#1399 [workflow] Fix PR title checker "fix fatal: bad revision 'master'" in release PR
  misc/check_pr_title.py
Labels: LGTM

#1354 [cc] Add struct compiler to the experimental C backend
  .github/workflows/persubmit.yml
  misc/hello.py
  taichi/backends/cc/cc_configuation.h
  taichi/backends/cc/cc_kernel.h
  taichi/backends/cc/cc_layout.h
  taichi/backends/cc/cc_program.cpp
  taichi/backends/cc/cc_program.h
  taichi/backends/cc/cc_utils.h
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/cc/struct_cc.cpp
  taichi/backends/cc/struct_cc.h
Labels: waiting for reply

#1344 [Lang] Add ti.static_assert for compile-time assertations
  .github/ISSUE_TEMPLATE/bug_report.md
  docs/debugging.rst
  docs/index.rst
  docs/syntax.rst
  python/taichi/lang/impl.py
  tests/python/test_assert.py
Labels: doc, python, waiting for reply

#1403 [opt] [refactor] Move advanced optimization toggle to "ti.cfg.advanced_optimization"
  misc/demo_constant_fold.py
  misc/demo_launch_overhead.py
  misc/demo_listgen.py
  taichi/ir/ir.cpp
  taichi/ir/ir.h
  taichi/program/compile_config.cpp
  taichi/program/compile_config.h
  taichi/python/export_lang.cpp
  taichi/transforms/constant_fold.cpp
  taichi/transforms/extract_constant.cpp
  taichi/transforms/offload.cpp
  taichi/transforms/simplify.cpp
  taichi/transforms/variable_optimization.cpp
  tests/cpp/test_simplify.cpp
Labels: LGTM

#1382 [GUI] Support mouse wheel event on Win32
  docs/gui.rst
  examples/keyboard.py
  python/taichi/misc/gui.py
  taichi/gui/gui.h
  taichi/gui/win32.cpp
  taichi/python/export_visual.cpp
Labels: LGTM

#1418 [GUI] Support mouse wheel event on Mac Cocoa
  taichi/gui/cocoa.cpp
Labels: LGTM

#1401 [Error] Raise an warning when a Taichi matrix have > 32 entries
  misc/prtags.json
  python/taichi/lang/matrix.py
Labels: LGTM, error-message, python, waiting for reply

#1424 [Bug] [lang] [std] Fix all potential matrix SSA violation by using element_wise_write_binary
  codecov.yml
  python/taichi/lang/matrix.py
  python/taichi/lang/ops.py
  tests/python/test_linalg.py
Labels: LGTM

#1422 [GUI] Get images from the current GUI using gui.get_image()
  docs/gui.rst
  python/taichi/misc/gui.py
  taichi/python/export_visual.cpp
Labels: LGTM

#1396 [Misc] [cli] Standardize ti.init(), now support log_level, gdb_trigger, advanced_optimization as kwargs
  docs/debugging.rst
  docs/global_settings.rst
  misc/demo_excepthook.py
  python/taichi/lang/__init__.py
  taichi/backends/cuda/codegen_cuda.cpp
  taichi/python/export_lang.cpp
  tests/python/test_runtime.py
Labels: LGTM, python

#1386 [Example] Add mass_spring_3d.py (an extension library usage demo)
  examples/mass_spring_3d.py
  python/taichi/misc/gui.py
Labels: skip ci, waiting for reply

#1388 [doc] Improve the developer installation documentation
  cmake/TaichiCXXFlags.cmake
  docs/dev_install.rst
  docs/index.rst
  docs/install.rst
  python/taichi/core/util.py
Labels: LGTM, doc

#1451 [doc] [example] Update faq.rst, add examples/revert_image_color.py
  docs/export_results.rst
  docs/faq.rst
  docs/global_settings.rst
  docs/hello.rst
  docs/index.rst
  docs/snode.rst
  examples/revert_image_color.py
Labels: LGTM

#1453 [Lang] Make tensor indicing automatically cast to int32 and raise an warning
  python/taichi/lang/impl.py
  taichi/transforms/type_check.cpp
  tests/python/test_indices.py
Labels: LGTM

#1465 [cli] [test] Add some useful pytest arguments
  python/taichi/main.py
Labels: LGTM

#1472 [doc] Fix LLVM version in dev_install.rst
  docs/dev_install.rst
Labels: small changeset

#1440 [Example] Add tree method n-body solver of O(n log n): tree_gravity.py
  examples/tree_gravity.py
  python/taichi/misc/gui.py
Labels: skip ci, waiting for reply

#1447 [cli] Print some useful links in CLI banner
  python/taichi/main.py
Labels: LGTM, waiting for reply

#1473 [Bug] [opt] Hotfix for wrong parallel assignments
  taichi/analysis/alias_analysis.cpp
  tests/python/test_optimization.py
Labels: LGTM

#1476 [Refactor] [lang] "ti.sqr(x)" is now fully deprecated
  docs/debugging.rst
  docs/meta.rst
  python/taichi/__init__.py
  python/taichi/lang/__init__.py
  python/taichi/lang/ops.py
  python/taichi/lang/util.py
  python/taichi/misc/error.py
  taichi/python/export_lang.cpp
Labels: has-oft-change, small changeset

#1409 [example] Update mpm_lagrangian_forces.py to new syntax
  examples/mpm_lagrangian_forces.py
Labels: waiting for reply

#1295 [doc] Add user utilities doc
  docs/index.rst
  docs/profiler.rst
  docs/utilities.rst
  python/taichi/__init__.py
  python/taichi/misc/util.py
Labels: waiting for reply

#1477 [PyPI] Remove dill, pytest, pytest-xdist from end-user hard dependencies
  python/taichi/lang/shell.py
  setup.py
Labels: dependency, small changeset

#1464 [test] Use @pytest.mark.forked to fix test_without_init
  misc/test_without_init.py
  tests/python/test_runtime.py
Labels: LGTM, small changeset

#1443 [Metal] Support fast_math, preps for saturating_grid_dim
  taichi/backends/metal/api.cpp
  taichi/backends/metal/api.h
  taichi/backends/metal/kernel_manager.cpp
  tests/python/test_element_wise.py
Labels: LGTM

#1485 [doc] Add matrix method documentation including normalized()
  docs/atomic.rst
  docs/install.rst
  docs/matrix.rst
  docs/vector.rst
  python/taichi/lang/matrix.py
Labels: LGTM

#1490 [GUI] Support slider, label and button as widgets
  docs/gui.rst
  examples/gui_widgets.py
  python/taichi/misc/gui.py
  taichi/gui/gui.h
  taichi/python/export_visual.cpp
Labels: LGTM

#1481 [metal] Misc tweaks to make #1480 easier to review
  taichi/backends/metal/codegen_metal.cpp
  taichi/backends/metal/kernel_manager.cpp
  taichi/backends/metal/shaders/runtime_structs.metal.h
  taichi/backends/metal/shaders/runtime_utils.metal.h
  taichi/backends/metal/struct_metal.cpp
Labels: large changeset, waiting for reply

#1468 [Lang] Support (a if cond else b) syntax in Taichi-scope
  python/taichi/lang/matrix.py
  python/taichi/lang/ops.py
  python/taichi/lang/transformer.py
  taichi/ir/expression_ops.h
  taichi/python/export_lang.cpp
  tests/python/test_element_wise.py
  tests/python/test_matrix.py
  tests/python/test_syntax_errors.py
Labels: LGTM

#1484 [doc] Fix code-block render issue in debugging.rst
  docs/debugging.rst
  python/taichi/lang/impl.py
Labels: small changeset

#1496 [Lang] Support "break" and "continue" in static-fors
  python/taichi/lang/transformer.py
  tests/python/test_static.py
Labels: LGTM, python

#1494 [cli] Remove the never used 'tid' command
  cmake/PythonNumpyPybind11.cmake
  python/build.py
  python/taichi/main.py
  setup.py
Labels: LGTM, small changeset

#1508 [Linux] [llvm] Fix LLVM symbol leakage to prevent conflict with other libs using LLVM like GLX
  cmake/TaichiCore.cmake
  misc/linker.map
Labels: LGTM, error-prone, small changeset

#1492 [Lang] Enhance warning system and support runtime assert message
  misc/demo_warning.py
  python/taichi/core/util.py
  python/taichi/lang/impl.py
  python/taichi/lang/matrix.py
  python/taichi/lang/transformer.py
  python/taichi/lang/util.py
  python/taichi/misc/gui.py
  python/taichi/misc/util.py
  tests/python/test_assert.py
Labels: LGTM

#1389 [doc] Update documentaion on meta programming for #1374
  docs/meta.rst
  docs/scalar_tensor.rst
  docs/snode.rst
  docs/vector.rst
Labels: LGTM, doc, waiting for reply

#1520 [GUI] Support gui.triangles() for batched triangle painting
  python/taichi/misc/gui.py
  taichi/gui/gui.cpp
  taichi/gui/gui.h
  taichi/python/export_visual.cpp
Labels: LGTM

#1529 [Example] Enhance nbody_oscillator.py with molecular force
  examples/nbody_oscillator.py
Labels: skip ci

#1528 [Bug] [cli] Fix environment variable TI_ARCH=xxx not work
  examples/mpm128.py
  examples/mpm99.py
  python/taichi/lang/__init__.py
  tests/python/test_runtime.py
Labels: has-oft-change, python, small changeset

#1515 [Doc] Update our documents from ti.var to ti.field
  docs/compilation.rst
  docs/debugging.rst
  docs/export_results.rst
  docs/external.rst
  docs/gui.rst
  docs/hello.rst
  docs/internal.rst
  docs/layout.rst
  docs/matrix.rst
  docs/odop.rst
  docs/offset.rst
  docs/profiler.rst
  docs/scalar_tensor.rst
  docs/snode.rst
  docs/vector.rst
Labels: doc, large changeset

#1521 [Example] [autodiff] Add FEM elastic simulator: fem99 and fem128
  examples/fem128.py
  examples/fem99.py
  taichi/backends/opengl/opengl_api.cpp
Labels: depends-other, skip ci

#1467 [lang] [refactor] Setup a multipass AST transformer
  python/taichi/lang/impl.py
  python/taichi/lang/kernel.py
  python/taichi/lang/transformer.py
Labels: LGTM, conflict-prone, error-prone, python

#1531 [Refactor] 'ti.Matrix(n, m, dt, shape)' is deprecated, use 'ti.Matrix.var(n, m, dt, shape)' instead
  .travis.yml
  python/taichi/lang/matrix.py
Labels: LGTM, python

#1510 [refactor] Better import order by using __all__
  python/taichi/__init__.py
  python/taichi/core/__init__.py
  python/taichi/core/settings.py
  python/taichi/core/util.py
  python/taichi/misc/__init__.py
  python/taichi/misc/gui.py
  python/taichi/misc/image.py
  python/taichi/misc/util.py
  python/taichi/tools/__init__.py
  python/taichi/tools/np2ply.py
  python/taichi/tools/video.py
Labels: LGTM, conflict-prone, error-prone, python

#1536 [cc] Support "range for" and "while" statement on C backend
  misc/cc_fractal.py
  misc/cc_hello.py
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/opengl/codegen_opengl.cpp
Labels: LGTM

#1544 [linux] Fix LLVM symbol leakage in release mode by using RTLD_GLOBAL
  python/taichi/core/util.py
  python/taichi/lang/matrix.py
Labels: LGTM, has-oft-change, small changeset

#1554 [opengl] Fix reversed nested for loops error on OpenGL
  examples/taichi_logo.py
  taichi/backends/opengl/codegen_opengl.cpp
Labels: LGTM

#1540 [opengl] [refactor] KernelParallelAttribs -> ParallelSize + virtual methods to make a way for grid-stride-loop
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_api.h
Labels: c++, enhancement, opengl, waiting for reply

#1553 [cc] The C backend is now capable of running mpm128
  examples/taichi_logo.py
  misc/cc_fractal.py
  misc/cc_hello.py
  taichi/backends/cc/cc_layout.h
  taichi/backends/cc/cc_program.cpp
  taichi/backends/cc/cc_program.h
  taichi/backends/cc/cc_runtime.h
  taichi/backends/cc/cc_utils.h
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/cc/context.h
  taichi/backends/cc/runtime/base.h
  taichi/backends/cc/struct_cc.cpp
  taichi/backends/cc/struct_cc.h
  taichi/lang_util.cpp
  taichi/program/program.cpp
Labels: LGTM, c++, large changeset

#1542 [OpenGL] [perf] Support grid-stride loop, use "ti.init(saturating_grid_dim=xxx)" to set stride size
  misc/test_grid_stride_loop.py
  python/taichi/lang/__init__.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/python/export_lang.cpp
Labels: c++, conflict-prone, opengl

#1543 [OpenGL] [refactor] Ensure SSBO number <= 8 in most situations for better compatbility
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_api.h
  taichi/backends/opengl/opengl_kernel_launcher.h
  taichi/backends/opengl/opengl_kernel_util.h
  taichi/backends/opengl/shaders/listman.h
  taichi/backends/opengl/shaders/runtime.h
Labels: c++, enhancement, error-prone, large changeset, opengl

#1566 [test] Skip mpm88 async on Appveyor
  tests/python/test_mpm88.py
Labels: small changeset

#1575 [gui] [error] [linux] Better error message when X display not available
  docs/scalar_tensor.rst
  docs/syntax.rst
  taichi/gui/x11.cpp
Labels: small changeset

#1581 [example] Upgrade mpm88 to new syntax
  examples/mpm88.py
Labels: GAMES201, LGTM

#1573 [OpenGL] Support 'ti.asm' to insert embed GLSL codes (experimental)
  python/taichi/lang/__init__.py
  python/taichi/lang/ops.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/inc/extensions.inc.h
  taichi/ir/frontend_ir.h
  taichi/ir/ir.cpp
  taichi/ir/ir.h
  taichi/program/extension.cpp
  taichi/python/export_lang.cpp
  tests/python/test_external_func.py
Labels: wait-release

#1588 [CC] [test] The C backend is now passing all the tests
  taichi/backends/cc/cc_program.h
  taichi/backends/cc/codegen_cc.cpp
  taichi/backends/cc/runtime/base.h
  taichi/program/extension.cpp
  tests/python/test_atomic.py
  tests/python/test_bitmasked.py
  tests/python/test_dynamic.py
  tests/python/test_struct_for_dynamic.py
Labels: wait-release

#1567 [opengl] [refactor] 3 misc refactors for OpenGL
  misc/test_grid_stride_loop.py
  python/taichi/lang/__init__.py
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_api.h
  taichi/backends/opengl/opengl_kernel_launcher.h
  taichi/backends/opengl/opengl_kernel_util.h
  taichi/backends/opengl/shaders/listman.h
  taichi/backends/opengl/shaders/runtime.h
  taichi/python/export_lang.cpp
Labels: wait-release

#1574 [OpenGL] [perf] Support TLS to improve reduction performance
  taichi/backends/metal/codegen_metal.cpp
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/program/compile_config.cpp
  taichi/program/compile_config.h
  taichi/python/export_lang.cpp
Labels: LGTM, wait-release

#1600 [opengl] [refactor] Fix TLS not working and refactor ParallelSize for grid-stride-loop
  taichi/backends/opengl/codegen_opengl.cpp
  taichi/backends/opengl/opengl_api.cpp
  taichi/backends/opengl/opengl_api.h
  tests/python/test_reduction.py
Labels: urgent

#1603 [GUI] Support gui.lines for batched line drawing
  docs/gui.rst
  examples/mpm88.py
  examples/mpm_lagrangian_forces.py
  python/taichi/misc/gui.py
  taichi/gui/gui.cpp
  taichi/gui/gui.h
  taichi/python/export_visual.cpp
Labels: LGTM

#1606 [Error] Improve error message when using non-global variables in global operations
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  python/taichi/lang/matrix.py
  taichi/common/core.h
  taichi/ir/expr.cpp
  taichi/python/export_lang.cpp
  tests/python/test_lexical_scope.py
Labels: LGTM

#1546 [IPython] 'ti.sync()' is no longer needed for 'print()' in OpenGL and Metal backend
  docs/debugging.rst
  misc/test_print.py
  python/taichi/lang/impl.py
  python/taichi/lang/kernel.py
  python/taichi/lang/shell.py
  taichi/python/export_misc.cpp
  taichi/python/print_buffer.h
Labels: waiting for reply

#1462 [test] [refactor] Add @ti.test decorators to unify testing infrastructure
  .gitignore
  pytest.ini
  python/taichi/__init__.py
  python/taichi/misc/__init__.py
  python/taichi/misc/test.py
  python/taichi/testing.py
  tests/conftest.py
  tests/python/test_test.py
Labels: LGTM, large changeset

#1475 [doc] Workflow for writing a Python test for #1462
  docs/contributor_guide.rst
  docs/index.rst
  docs/utilities.rst
  docs/write_test.rst
  misc/prtags.json
Labels: LGTM, depends-other, doc, large changeset, skip ci

#1605 [misc] [refactor] 'ti.vec' and 'ti.veci' is deprecated, directly use a tuple in GUI system instead
  docs/gui.rst
  examples/pbf2d.py
  python/taichi/misc/gui.py
  python/taichi/misc/util.py
Labels: LGTM

#1550 [Doc] [autodiff] Update documentations on autodiff
  docs/autodiff.rst
  docs/differentiable_programming.rst
  docs/layout.rst
  docs/odop.rst
  examples/ad_gravity.py
  taichi/transforms/reverse_segments.cpp
Labels: waiting for reply
