Repository taichi-dev/taichi, pull requests merged in 2021-09, with the labels that each got.

#2881 [ci] Build and Release Vulkan in CI/CD
  .github/workflows/presubmit.yml
  .github/workflows/release.yml
  ci/Dockerfile
  cmake/TaichiCore.cmake
Labels: ci, vulkan

#2987 [Doc] Remove 'Versioning and releases'; Fix 'Documentation writing guide'
  docs/lang/articles/contribution/doc_writing.md
  docs/lang/articles/contribution/versioning_releases.md
Labels: skip ci

#3005 [Doc] Fix typo in data_oriented docstring
  python/taichi/lang/kernel_impl.py
Labels: skip ci

#3002 [Doc] Improve the documentation for debugging and GGUI
  docs/lang/articles/misc/debugging.md
  docs/lang/articles/misc/ggui.md
Labels: doc, skip ci

#3009 [Doc] Update metaprogramming doc
  docs/lang/articles/advanced/meta.md
Labels: skip ci

#3010 [Doc] Update the Type system section
  docs/lang/articles/basic/type.md
Labels: skip ci

#3028 [vulkan] Disable validation layer with release builds
  taichi/backends/vulkan/embedded_device.cpp
Labels: vulkan

#2990 [Doc] Add documentation for TLS/BLS
  docs/lang/articles/advanced/performance.md
  docs/lang/articles/static/assets/bls_indices_mapping.png
Labels: skip ci

#3036 [LLVM] Rename runtime memory allocation function
  taichi/runtime/llvm/runtime.cpp
  taichi/system/snode_tree_buffer_manager.cpp
Labels: enhancement, c++

#3000 [Doc] Update interacting with external arrays
  docs/lang/articles/basic/external.md
Labels: skip ci

#2994 [Doc] Update field
  docs/lang/articles/basic/field.md
Labels: skip ci

#2997 [Doc] Performance tuning update
  docs/lang/articles/advanced/performance.md
Labels: skip ci

#2996 [Doc] Developer installation update
  docs/lang/articles/contribution/dev_install.md
Labels: skip ci

#3040 [Doc] Update cpp_style.md
  docs/lang/articles/contribution/cpp_style.md
Labels: skip ci

#2999 [Doc] Update kernels and functions
  docs/lang/articles/basic/syntax.md
Labels: skip ci

#3042 [Doc] Fix Arch Linux building guide clang dependence
  docs/lang/articles/contribution/dev_install.md
Labels: skip ci

#3014 [Doc] Improve the documentation for profiler
  docs/lang/articles/misc/profiler.md
Labels: skip ci

#3011 [Doc] Update Python test doc
  docs/lang/articles/contribution/write_test.md
Labels: skip ci

#3043 [Doc] Update Type system
  docs/lang/articles/basic/type.md
Labels: skip ci
