Repository taichi-dev/taichi, pull requests merged in 2022-09, with the labels that each got.

#5992 [cuda] Use CUDA primary context to work with PyTorch and Numba.
  taichi/rhi/cuda/cuda_context.cpp
  taichi/rhi/cuda/cuda_driver_functions.inc.h
  taichi/runtime/llvm/llvm_runtime_executor.cpp
Labels: full-ci

#5783 [Lang] Indexing for new local matrix implementation
  python/taichi/_funcs.py
  python/taichi/_kernels.py
  python/taichi/lang/_ndrange.py
  python/taichi/lang/ast/ast_transformer.py
  python/taichi/lang/impl.py
  python/taichi/lang/kernel_arguments.py
  python/taichi/lang/matrix.py
  taichi/codegen/cuda/codegen_cuda.cpp
  taichi/codegen/llvm/codegen_llvm.cpp
  taichi/ir/frontend_ir.cpp
  taichi/ir/statements.h
  taichi/ir/transforms.h
  taichi/ir/type.h
  taichi/runtime/llvm/llvm_context.cpp
  taichi/transforms/cfg_optimization.cpp
  taichi/transforms/compile_to_offloads.cpp
  taichi/transforms/simplify.cpp
  taichi/transforms/type_check.cpp
  tests/python/test_matrix.py
  tests/python/test_scalar_op.py
Labels: full-ci

#6062 [Mesh] [bug] Fix nested mesh for
  python/taichi/lang/ast/ast_transformer.py
Labels: mesh

#5846 [ci] Use local caches on self-hosted runners, and code refactoring.
  .github/workflows/release.yml
  .github/workflows/scripts/android-build.sh
  .github/workflows/scripts/common-utils.ps1
  .github/workflows/scripts/common-utils.sh
  .github/workflows/scripts/unix-build.sh
  .github/workflows/scripts/unix_build.sh
  .github/workflows/scripts/unix_test.sh
  .github/workflows/scripts/win_build.ps1
  .github/workflows/scripts/win_build_test_cpu.ps1
  .github/workflows/scripts/win_test.ps1
  .github/workflows/testing.yml
  ci/Dockerfile.ubuntu.18.04.cpu
  ci/windows/Dockerfile_cpu
Labels: ci, full-ci

#6124 [bug] Let every thread has its own CompileConfig
  cpp_examples/aot_save.cpp
  python/taichi/ad/_ad.py
  python/taichi/lang/any_array.py
  python/taichi/lang/ast/ast_transformer.py
  python/taichi/lang/expr.py
  python/taichi/lang/impl.py
  python/taichi/lang/kernel_impl.py
  python/taichi/lang/mesh.py
  python/taichi/lang/misc.py
  python/taichi/lang/simt/block.py
  python/taichi/linalg/sparse_solver.py
  python/taichi/ui/canvas.py
  taichi/codegen/cc/codegen_cc.cpp
  taichi/codegen/codegen.cpp
  taichi/codegen/cpu/codegen_cpu.cpp
  taichi/codegen/cuda/codegen_cuda.cpp
  taichi/codegen/dx12/codegen_dx12.cpp
  taichi/codegen/llvm/codegen_llvm.cpp
  taichi/codegen/llvm/codegen_llvm_quant.cpp
  taichi/codegen/spirv/spirv_codegen.cpp
  taichi/codegen/wasm/codegen_wasm.cpp
  taichi/program/compile_config.h
  taichi/program/function.cpp
  taichi/program/ir_node_extended_impl.cpp
  taichi/program/kernel.cpp
  taichi/program/program.cpp
  taichi/program/program.h
  taichi/python/export_lang.cpp
  taichi/runtime/gfx/runtime.cpp
  taichi/transforms/constant_fold.cpp
  tests/cpp/backends/dx11_device_test.cpp
  tests/cpp/ir/frontend_type_inference_test.cpp
  tests/cpp/transforms/alg_simp_test.cpp
  tests/cpp/transforms/simplify_test.cpp
Labels: full-ci

#6072 [opt] Cache loop-invariant global vars to local vars
  taichi/ir/transforms.h
  taichi/program/compile_config.h
  taichi/python/export_lang.cpp
  taichi/transforms/cache_loop_invariant_global_vars.cpp
  taichi/transforms/compile_to_offloads.cpp
  taichi/transforms/loop_invariant_code_motion.cpp
  taichi/transforms/loop_invariant_detector.h
Labels: full-ci

#6160 [metal] Maintain a print string table per kernel
  taichi/codegen/metal/codegen_metal.cpp
  taichi/codegen/metal/codegen_metal.h
  taichi/runtime/metal/aot_module_builder_impl.cpp
  taichi/runtime/metal/aot_module_builder_impl.h
  taichi/runtime/metal/aot_module_loader_impl.cpp
  taichi/runtime/metal/kernel_manager.cpp
  taichi/runtime/metal/kernel_manager.h
  taichi/runtime/metal/kernel_utils.cpp
  taichi/runtime/metal/kernel_utils.h
Labels: full-ci

#6169 [llvm] MatrixField refactor 7/n: Simplify codegen for TensorType allocation and access
  taichi/codegen/llvm/codegen_llvm.cpp
  taichi/ir/statements.h
  taichi/runtime/llvm/llvm_context.cpp
Labels: full-ci

#6194 [Lang] MatrixField refactor 9/n: Allow dynamic index of matrix field when real_matrix=True
  taichi/transforms/lower_matrix_ptr.cpp
  tests/python/test_matrix.py
Labels: full-ci
