Repository taichi-dev/taichi, pull requests merged in 2022-08, with the labels that each got.

#5626 [ci] Only run portion of tests on PR draft
  .github/workflows/release.yml
  .github/workflows/scripts/unix_test.sh
  .github/workflows/scripts/win_test.ps1
  .github/workflows/testing.yml
  tests/python/examples/algorithm/test_laplace.py
  tests/python/examples/algorithm/test_print_offset.py
  tests/python/examples/autodiff/test_minimization.py
  tests/python/examples/autodiff/test_regression.py
  tests/python/examples/autodiff/test_simple_derivative.py
  tests/python/examples/rendering/test_cornell_box.py
  tests/python/examples/rendering/test_taichi_logo.py
  tests/python/examples/simulation/test_ad_gravity.py
  tests/python/examples/simulation/test_mpm99.py
  tests/python/examples/simulation/test_nbody.py
  tests/test_utils.py
Labels: enhancement, ci

#5734 [ci] Prevent using the offline cache of previous jobs
  .github/workflows/scripts/unix_test.sh
  .github/workflows/scripts/win_test.ps1
Labels: full-ci

#5789 [ci] Workaround nightly C++ test crash
  .github/workflows/release.yml
  .github/workflows/scripts/unix_test.sh
  .github/workflows/testing.yml
  ci/Dockerfile.ubuntu.18.04
Labels: ci

#5815 [ci] Regenerate AOT binaries for every Android smoke test
  .github/workflows/scripts/aot-demo.sh
  .github/workflows/scripts/common-utils.sh
  .github/workflows/scripts/unix-build-v2.sh
  .github/workflows/testing.yml
  ci/Dockerfile.android-sdk.18.04
  ci/Dockerfile.ubuntu.18.04
Labels: ci

#5836 [example] Making gravity option used in stable_fluid_ggui.py
  python/taichi/examples/ggui_examples/stable_fluid_ggui.py
Labels: full-ci

#5898 [refactor] [ir] Remove legacy LaneAttribute usage from ExternalPtrStmt/GlobalPtrStmt
  taichi/analysis/alias_analysis.cpp
  taichi/analysis/bls_analyzer.cpp
  taichi/analysis/gather_snode_read_writes.cpp
  taichi/analysis/gather_uniquely_accessed_pointers.cpp
  taichi/analysis/mesh_bls_analyzer.cpp
  taichi/analysis/same_statements.cpp
  taichi/codegen/cc/codegen_cc.cpp
  taichi/codegen/llvm/codegen_llvm.cpp
  taichi/codegen/metal/codegen_metal.cpp
  taichi/codegen/spirv/spirv_codegen.cpp
  taichi/ir/control_flow_graph.cpp
  taichi/ir/statements.cpp
  taichi/ir/statements.h
  taichi/transforms/auto_diff.cpp
  taichi/transforms/bit_loop_vectorize.cpp
  taichi/transforms/check_out_of_bound.cpp
  taichi/transforms/demote_atomics.cpp
  taichi/transforms/detect_read_only.cpp
  taichi/transforms/flag_access.cpp
  taichi/transforms/ir_printer.cpp
  taichi/transforms/lower_access.cpp
  taichi/transforms/make_block_local.cpp
  taichi/transforms/make_mesh_block_local.cpp
  taichi/transforms/make_thread_local.cpp
  taichi/transforms/type_check.cpp
Labels: full-ci

#5901 [refactor] [ir] Remove legacy LaneAttribute
  taichi/analysis/arithmetic_interpretor.cpp
  taichi/analysis/data_source_analysis.cpp
  taichi/analysis/value_diff.cpp
  taichi/analysis/verify.cpp
  taichi/codegen/cc/codegen_cc.cpp
  taichi/codegen/llvm/codegen_llvm.cpp
  taichi/codegen/metal/codegen_metal.cpp
  taichi/codegen/spirv/spirv_codegen.cpp
  taichi/ir/control_flow_graph.cpp
  taichi/ir/frontend_ir.cpp
  taichi/ir/ir.h
  taichi/ir/ir_builder.cpp
  taichi/ir/statements.cpp
  taichi/ir/statements.h
  taichi/transforms/alg_simp.cpp
  taichi/transforms/auto_diff.cpp
  taichi/transforms/binary_op_simplify.cpp
  taichi/transforms/bit_loop_vectorize.cpp
  taichi/transforms/check_out_of_bound.cpp
  taichi/transforms/constant_fold.cpp
  taichi/transforms/demote_mesh_statements.cpp
  taichi/transforms/demote_operations.cpp
  taichi/transforms/ir_printer.cpp
  taichi/transforms/lower_ast.cpp
  taichi/transforms/make_block_local.cpp
  taichi/transforms/make_mesh_block_local.cpp
  taichi/transforms/make_mesh_thread_local.cpp
  taichi/transforms/offload.cpp
  taichi/transforms/simplify.cpp
  taichi/transforms/type_check.cpp
  taichi/transforms/unreachable_code_elimination.cpp
  tests/cpp/analysis/same_statements_test.cpp
  tests/cpp/ir/ir_test.cpp
  tests/cpp/ir/stmt_field_manager_test.cpp
  tests/cpp/transforms/binary_op_simplify_test.cpp
Labels: full-ci
