Repository taichi-dev/taichi, pull requests merged in 2023-04, with the labels that each got.

#7716 [bug] Switch the gallery image used by README.
  README.md
Labels: doc

#7739 [ci] Skip large shared memory test for Turing GPUs.
  tests/python/test_shared_array.py
Labels: full-ci

#7682 [gui] Fluid visualization utilities
  python/taichi/tools/__init__.py
  python/taichi/tools/vtk.py
  python/taichi/ui/canvas.py
  python/taichi/ui/gui.py
  requirements_test.txt
Labels: gui
